### ISSUE TITLE
Play custom segment of an animation.

### ISSUE THREAD

**Issue by alexander-mozolevsky** [react-native-community/lottie-react-native#614]
Hello guys,

Tried to find solution for next issue:

I have an animation,
an animation of light flame of a candle

So, there are 3 "parts" in this animation:
1) flame starts
2) flame animation
3) flame stops

In some cases I need to run 1) and 2)
And in some time run 3).

How can it be done within one lottie animation?

Saw there is `playSegments` method for web, but not for RN.

Thank you.

**Comment by sclavijo93** [comment]
Hi, I need something like that too, can anyone help us please?

**Comment by alexander-mozolevsky** [comment]
@sclavijo93 
Here is a solution: 
```
this.animation.play(startFrame, endFrame);

 - for example

this.animation.play(30, 120);
```

This will work, closing issue.

**Comment by sclavijo93** [comment]
@alexander-mozolevsky 
Hmmm, it seems like I need something different here. I have a Lottie that has an introduction from frame 0 to 120, then I want to loop from the frame 120 to 720

**Comment by alexander-mozolevsky** [comment]
@sclavijo93 I had the same animation, my solution was:

You need change source frames of the animation when it's finished, example:
You need to start animation from 0 to 120 frame, then use `onAnimationFinish` callback to change source frames from 120 to 720, and set `loop` to `true`.

So, play from 0 to 120, create callback `onAnimationFinish` and change source dynamically (using state for example) from 120 to 720 and set `loop` to true.

That should work.

**Comment by sclavijo93** [comment]
Hey @alexander-mozolevsky , thank you so much. It worked like a charm.

**Comment by teellis20** [comment]
Hey @alexander-mozolevsky / @sclavijo93 how were you able to set the `loop` to true? I was able to set the reference to set the `animation.current.play(120,720)` but not the `loop`. Being able to start from the frame I want works but it keeps running the `onAnimationFinish()` callback every loop which I feel can't be great for performance, since if `loop:{true}` the `onAnimationFinish()` callback would stop running. 

here's my code: when I logged `fireAnimation.current` I was able to find the loop in the `fireAnimation.current.props` object but wasn't able to change it to true. 
`onAnimationFinish={() => {
                console.log('how many times does this play?');
                fireAnimation.current.props.loop = true;
                fireAnimation.current.play(12,39);
            }}
`

Thanks for the help!
